apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-operator
  template:
    metadata:
      labels:
        app: group-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - -alsologtostderr
        image: coreweave/group-operator:latest
      serviceAccountName: group-operator
