apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- coreweave.com_groupjobs.yaml
- deployment.yaml
- service-account.yaml
images:
- name: coreweave/group-operator
  newName: coreweave/group-operator
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app: group-operator
    app.kubernetes.io/component: groupjob
    app.kubernetes.io/name: group-operator
    kustomize.component: group-operator
