apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: group-operator
images:
- name: mpioperator/group-operator
  newName: mpioperator/group-operator
  newTag: master
patches:
- path: ./patch.yaml
  target:
    group: apps
    kind: Deployment
    name: group-operator
    version: v1
labels:
- includeSelectors: true
  pairs:
    app: group-operator
    app.kubernetes.io/component: groupjob
    app.kubernetes.io/name: group-operator
    kustomize.component: group-operator
