// Copyright 2025 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	v2beta1 "github.com/coreweave/group-operator/pkg/apis/kubeflow/v2beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// GroupJobLister helps list GroupJobs.
// All objects returned here must be treated as read-only.
type GroupJobLister interface {
	// List lists all GroupJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.GroupJob, err error)
	// GroupJobs returns an object that can list and get GroupJobs.
	GroupJobs(namespace string) GroupJobNamespaceLister
	GroupJobListerExpansion
}

// mPIJobLister implements the GroupJobLister interface.
type mPIJobLister struct {
	listers.ResourceIndexer[*v2beta1.GroupJob]
}

// NewGroupJobLister returns a new GroupJobLister.
func NewGroupJobLister(indexer cache.Indexer) GroupJobLister {
	return &mPIJobLister{listers.New[*v2beta1.GroupJob](indexer, v2beta1.Resource("mpijob"))}
}

// GroupJobs returns an object that can list and get GroupJobs.
func (s *mPIJobLister) GroupJobs(namespace string) GroupJobNamespaceLister {
	return mPIJobNamespaceLister{listers.NewNamespaced[*v2beta1.GroupJob](s.ResourceIndexer, namespace)}
}

// GroupJobNamespaceLister helps list and get GroupJobs.
// All objects returned here must be treated as read-only.
type GroupJobNamespaceLister interface {
	// List lists all GroupJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.GroupJob, err error)
	// Get retrieves the GroupJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2beta1.GroupJob, error)
	GroupJobNamespaceListerExpansion
}

// mPIJobNamespaceLister implements the GroupJobNamespaceLister
// interface.
type mPIJobNamespaceLister struct {
	listers.ResourceIndexer[*v2beta1.GroupJob]
}
